plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.helloworld'
    compileSdk 36

    defaultConfig {
        minSdk 21 // 不能比项目的更小

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

}

dependencies {
    compileOnly fileTree(include: ['*.aar'], dir: './libs')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'com.google.android.material:material:1.10.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    implementation "com.squareup.okhttp3:okhttp:3.12.12"
    implementation 'com.alibaba:fastjson:1.2.83'
    implementation project(':s-file-picker')
    implementation project(':common')
}